name: Demo Org CI-CD
on:
  push:
    branches: [ $default_branch ]
  pull_request:
    branches: [ $default_branch ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout Repo
        uses: actions/checkout@v4
      - name: Setup NodeIs - 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm install
      - name: Unit Testing
        run: npm test --if-present
      - name: Run codecoverage
        run: npm run coverage --if-present
